# Generated by Django 3.2.4 on 2021-06-14 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Заполните текст ответа', max_length=255, unique=True, verbose_name='Вариант ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заполните название голосования', max_length=200, unique=True, verbose_name='Название голосования')),
                ('description', models.TextField(blank=True, help_text='Заполните описание голосования', verbose_name='Описание голосования')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата заполняется автоматически', verbose_name='Дата публикации')),
                ('active', models.BooleanField(default=True, help_text='Выберите активно ли голосование', verbose_name='Активность голосования')),
                ('creator', models.ForeignKey(help_text='Организатор голосования выбирается автоматически', on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL, verbose_name='Организатор голосования')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.ForeignKey(help_text='Выберите вариант ответа', on_delete=django.db.models.deletion.CASCADE, to='api.choice', verbose_name='Вариант ответа')),
                ('poll_id', models.ForeignKey(help_text='Выберите голосование', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.poll', verbose_name='Голос')),
                ('voter', models.ForeignKey(help_text='Избиратель выбирается автоматически', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='Избиратель')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='poll_id',
            field=models.ForeignKey(help_text='Выберите голосование', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.poll', verbose_name='Голос'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'poll_id', 'choice_id'), name='unique_vote'),
        ),
    ]
