# Generated by Django 3.2.4 on 2021-06-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote',
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll_id',
            field=models.ForeignKey(help_text='Выберите голосование', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.poll', verbose_name='Голосование'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll_id',
            field=models.ForeignKey(help_text='Выберите голосование', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.poll', verbose_name='Голосование'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'poll_id'), name='unique_vote'),
        ),
    ]
