# Generated by Django 3.2.4 on 2021-06-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210614_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice_id',
            field=models.ForeignKey(help_text='Выберите вариант ответа', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.choice', verbose_name='Вариант ответа'),
        ),
    ]
